CREATE TABLE Ruta  
( 
    Id_ruta INT CONSTRAINT pk_ruta PRIMARY KEY,
	Cod_plecare VARCHAR(3) ,
	Cod_destinatie VARCHAR(3),

CONSTRAINT ruta_invalida CHECK (Cod_destinatie <> Cod_plecare)
)

ALTER TABLE Ruta ADD CONSTRAINT COD_PLEACARE_FK FOREIGN KEY (Cod_plecare) REFERENCES Aeroport(Cod_aeroport) ON DELETE CASCADE;

INSERT INTO Ruta VALUES (1001, 'OTP', 'BCM');
INSERT INTO Ruta VALUES (5001,'BCM', 'OTP');   
INSERT INTO Ruta VALUES (1002, 'OTP', 'CLJ');
INSERT INTO Ruta VALUES (2001, 'CLJ', 'OTP');  
INSERT INTO Ruta VALUES (1003, 'OTP', 'IAS');
INSERT INTO Ruta VALUES (3001, 'IAS', 'OTP');
INSERT INTO Ruta VALUES (3002, 'IAS', 'CLJ');
INSERT INTO Ruta VALUES (5002, 'BCM', 'IAS');
INSERT INTO Ruta VALUES (5010, 'BCM', 'FCO');
INSERT INTO Ruta VALUES (5011, 'BCM' , 'LTN');
INSERT INTO Ruta VALUES (5013, 'BCM', 'ATH');

INSERT INTO Ruta VALUES (1010, 'OTP', 'FCO');
INSERT INTO Ruta VALUES (1011, 'OTP', 'LTN');
INSERT INTO Ruta VALUES (1013, 'OTP', 'ATH');
INSERT INTO Ruta VALUES (101, 'FCO', 'LTN');
INSERT INTO Ruta VALUES (1101, 'LTN', 'OTP');
INSERT INTO Ruta VALUES (3101, 'ATH', 'OTP');
INSERT INTO Ruta VALUES (3014, 'IAS', 'CIA');
INSERT INTO Ruta VALUES (4103, 'CIA', 'IAS');
INSERT INTO Ruta VALUES (2014, 'CLJ', 'CIA');
INSERT INTO Ruta VALUES (4102, 'CIA', 'CLJ');
INSERT INTO Ruta VALUES (1016, 'OTP', 'NAP');
INSERT INTO Ruta VALUES (6101, 'NAP', 'OTP');
INSERT INTO Ruta VALUES (1017, 'OTP', 'MXP');
INSERT INTO Ruta VALUES (7101, 'MXP', 'OTP');
INSERT INTO Ruta VALUES (1018, 'OTP', 'SKG');
INSERT INTO Ruta VALUES (8101, 'SKG', 'OTP');
INSERT INTO Ruta VALUES (1019, 'OTP', 'CFU');
INSERT INTO Ruta VALUES (9101, 'CFU', 'OTP');
INSERT INTO Ruta VALUES (1020, 'OTP', 'BER');
INSERT INTO Ruta VALUES (201, 'BER', 'OTP');
INSERT INTO Ruta VALUES (1021, 'OTP', 'VLC');
INSERT INTO Ruta VALUES (1201, 'VLC', 'OTP');


INSERT INTO Ruta VALUES (2101, 'CLJ', 'BER');
INSERT INTO Ruta VALUES (1112, 'BER', 'CLJ');
INSERT INTO Ruta VALUES (2102, 'CLJ', 'CPH');
INSERT INTO Ruta VALUES (2112, 'CPH', 'CLJ');
INSERT INTO Ruta VALUES (2105, 'CLJ', 'LCA');
INSERT INTO Ruta VALUES (2115, 'LCA', 'CLJ');
INSERT INTO Ruta VALUES (3451, 'LCA', 'ATH');
INSERT INTO Ruta VALUES (5431, 'ATH', 'LCA');
INSERT INTO Ruta VALUES (2130, 'CLJ', 'CDG');
INSERT INTO Ruta VALUES (312, 'CDG', 'CLJ');


INSERT INTO Ruta VALUES (121, 'OTP', 'LIS');
INSERT INTO Ruta VALUES (1210, 'LIS', 'OTP');
INSERT INTO Ruta VALUES (151, 'OTP', 'AMS');
INSERT INTO Ruta VALUES (1510, 'AMS', 'OTP');
INSERT INTO Ruta VALUES (78, 'AMS', 'CPH');
INSERT INTO Ruta VALUES (87, 'CPH', 'AMS');

INSERT INTO Ruta VALUES (1111, 'BCM', 'VLC');
INSERT INTO Ruta VALUES (1110, 'VLC', 'BCM');

INSERT INTO Ruta VALUES (2032, 'IAS', 'MXP');
INSERT INTO Ruta VALUES (2302, 'MXP', 'IAS');
INSERT INTO Ruta VALUES (2319, 'SKG', 'ATH');
INSERT INTO Ruta VALUES (2320, 'ATH', 'SKG');
INSERT INTO Ruta VALUES (2333, 'ATH', 'CFU');
INSERT INTO Ruta VALUES (3332, 'CFU', 'ATH');
INSERT INTO Ruta VALUES (7501, 'BER', 'CDG');
INSERT INTO Ruta VALUES (7510, 'CDG', 'BER');

INSERT INTO Ruta VALUES (8011, 'LCA', 'IST');
INSERT INTO Ruta VALUES (8110, 'IST', 'LCA');

INSERT INTO Ruta VALUES (4051, 'IAS', 'LIS');
INSERT INTO Ruta VALUES (4510, 'LIS', 'IAS');


SELECT * 
FROM Ruta;


DROP TABLE Ruta;

DELETE FROM Ruta 
where cod_destinatie='OTP';

DELETE FROM Aeroport 
WHERE Cod_aeroport = 'OTP';
